import 'package:flutter/material.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedGroup99Widget1.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedEllipse48Widget4.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedGroup100Widget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedEduSwappWidget2.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedEducationsForyouWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedGroup72Widget4.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedGroup101Widget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedStatusBarWidget4.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedGroup99Widget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget2/generated/GeneratedEllipse47Widget4.dart';

/* Frame Explore
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExploreWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1504.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1504.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 207.0,
                              top: -175.0,
                              right: null,
                              bottom: null,
                              width: 342.0,
                              height: 342.0,
                              child: GeneratedEllipse47Widget4(),
                            ),
                            Positioned(
                              left: -11.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child: GeneratedStatusBarWidget4(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 217.0,
                              right: null,
                              bottom: null,
                              width: 294.0,
                              height: 81.0,
                              child: GeneratedEduSwappWidget2(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 314.0,
                              right: null,
                              bottom: null,
                              width: 172.0,
                              height: 32.0,
                              child: GeneratedEducationsForyouWidget(),
                            ),
                            Positioned(
                              left: -85.0,
                              top: -239.0,
                              right: null,
                              bottom: null,
                              width: 445.0,
                              height: 406.0,
                              child: GeneratedEllipse48Widget4(),
                            ),
                            Positioned(
                              left: 3.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 352.00543212890625,
                              height: 51.5,
                              child: GeneratedGroup72Widget4(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 427.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 226.0,
                              child: GeneratedGroup99Widget(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 691.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 226.0,
                              child: GeneratedGroup99Widget1(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 955.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 226.0,
                              child: GeneratedGroup100Widget(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 1219.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 226.0,
                              child: GeneratedGroup101Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
