import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/eduswappapp/generatedgroupwidget31/generated/GeneratedVectorWidget116.dart';
import 'package:flutterapp/eduswappapp/generatedgroupwidget31/generated/GeneratedVectorWidget117.dart';

/* Group Group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroupWidget31 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: -0.68,
            b: 0.73,
            c: 0.73,
            d: 0.68,
            child: Opacity(
              opacity: 0.6000000238418579,
              child: Container(
                width: 139.4140625,
                height: 159.83935546875,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.926385410829364;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  129.15115356445312;

                          double percentHeight = 0.9554890049213229;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  152.72474670410156;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: 0,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget116())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.23492763751225834;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  32.75221633911133;

                          double percentHeight = 0.17926136385332564;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  28.65302085876465;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.7650723351253853,
                                translateY:
                                    constraints.maxHeight * 0.8207386719454042,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget117())
                          ]);
                        }),
                      )
                    ]),
              ),
            )));
  }
}
