import 'package:flutter/material.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedRectangle196Widget1.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedLearnFromTheExpertWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedEllipse48Widget5.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedGroup72Widget5.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedRectangle194Widget2.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedMatchforEduWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedRectangle193Widget3.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedGiveEducationWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedSignOutWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedEllipse47Widget5.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedRectangle195Widget1.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget3/generated/GeneratedStatusBarWidget5.dart';

/* Frame Explore
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExploreWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -37.0,
                top: -210.0,
                right: null,
                bottom: null,
                width: 445.0,
                height: 406.0,
                child: GeneratedEllipse48Widget5(),
              ),
              Positioned(
                left: 207.0,
                top: -175.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 342.0,
                child: GeneratedEllipse47Widget5(),
              ),
              Positioned(
                left: -11.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget5(),
              ),
              Positioned(
                left: 94.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 81.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 48.0,
                child: GeneratedRectangle194Widget2(),
              ),
              Positioned(
                left: 117.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 27.0,
                child: GeneratedMatchforEduWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 48.0,
                child: GeneratedRectangle193Widget3(),
              ),
              Positioned(
                left: 77.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 27.0,
                child: GeneratedLearnFromTheExpertWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 48.0,
                child: GeneratedRectangle195Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 48.0,
                child: GeneratedRectangle196Widget1(),
              ),
              Positioned(
                left: 141.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 27.0,
                child: GeneratedSignOutWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 27.0,
                child: GeneratedGiveEducationWidget(),
              ),
              Positioned(
                left: 3.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 352.00543212890625,
                height: 51.5,
                child: GeneratedGroup72Widget5(),
              )
            ]),
      ),
    ));
  }
}
