import 'package:flutter/material.dart';
import 'package:flutterapp/eduswappapp/generatedgroup98widget/generated/GeneratedProductCatalogueWidget.dart';
import 'package:flutterapp/eduswappapp/generatedgroup98widget/generated/GeneratedProductPageWidget.dart';

/* Group Group 98
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup98Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1999.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 360.0,
                    height: 1999.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 360.0,
                            height: 1059.0,
                            child: GeneratedProductCatalogueWidget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 1185.0,
                            right: null,
                            bottom: null,
                            width: 360.0,
                            height: 814.0,
                            child: GeneratedProductPageWidget(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
