import 'package:flutter/material.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget4/generated/GeneratedCongratsWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget4/generated/GeneratedEllipse48Widget6.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget4/generated/GeneratedGroup72Widget6.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget4/generated/GeneratedYouhavematchedwithWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget4/generated/GeneratedFrame50Widget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget4/generated/GeneratedEllipse47Widget6.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget4/generated/GeneratedStatusBarWidget6.dart';

/* Frame Explore
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExploreWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 900.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 900.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -37.0,
                              top: -210.0,
                              right: null,
                              bottom: null,
                              width: 445.0,
                              height: 406.0,
                              child: GeneratedEllipse48Widget6(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: -175.0,
                              right: null,
                              bottom: null,
                              width: 342.0,
                              height: 342.0,
                              child: GeneratedEllipse47Widget6(),
                            ),
                            Positioned(
                              left: 3.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 352.00543212890625,
                              height: 51.5,
                              child: GeneratedGroup72Widget6(),
                            ),
                            Positioned(
                              left: -11.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child: GeneratedStatusBarWidget6(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 167.0,
                              right: null,
                              bottom: null,
                              width: 279.0,
                              height: 81.0,
                              child: GeneratedCongratsWidget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 256.0,
                              right: null,
                              bottom: null,
                              width: 287.0,
                              height: 66.0,
                              child: GeneratedYouhavematchedwithWidget(),
                            ),
                            Positioned(
                              left: 67.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 226.0,
                              height: 80.0,
                              child: GeneratedFrame50Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
