import 'package:flutter/material.dart';

/* UndefinedNode Listbox Component
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListboxComponentWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
