import 'package:flutter/material.dart';

/* Text Change data here.
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChangedatahereWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Change data here.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 26.0,
        fontFamily: 'Montserrat',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
