import 'package:flutter/material.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedEllipse48Widget3.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedKisiWidget1.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedKisiWidget2.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedKisiWidget.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedStatusBarWidget3.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedMATCHESWidget.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedEllipse47Widget3.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedGroup72Widget3.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedRectangle193Widget2.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedSKIPWidget.dart';
import 'package:flutterapp/eduswappapp/generatedmatchedwidget/generated/GeneratedKisiWidget3.dart';

/* Frame MATCHED
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMATCHEDWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 800.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: -37.0,
              top: -210.0,
              right: null,
              bottom: null,
              width: 445.0,
              height: 406.0,
              child: GeneratedEllipse48Widget3(),
            ),
            Positioned(
              left: 3.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 352.00543212890625,
              height: 51.5,
              child: GeneratedGroup72Widget3(),
            ),
            Positioned(
              left: 207.0,
              top: -175.0,
              right: null,
              bottom: null,
              width: 342.0,
              height: 342.0,
              child: GeneratedEllipse47Widget3(),
            ),
            Positioned(
              left: -11.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedStatusBarWidget3(),
            ),
            Positioned(
              left: 62.0,
              top: 202.0,
              right: null,
              bottom: null,
              width: 241.0,
              height: 68.0,
              child: GeneratedMATCHESWidget(),
            ),
            Positioned(
              left: 46.0,
              top: 296.0,
              right: null,
              bottom: null,
              width: 268.7183532714844,
              height: 40.0,
              child: GeneratedKisiWidget(),
            ),
            Positioned(
              left: 46.0,
              top: 346.0,
              right: null,
              bottom: null,
              width: 268.7183532714844,
              height: 40.0,
              child: GeneratedKisiWidget1(),
            ),
            Positioned(
              left: 46.0,
              top: 396.0,
              right: null,
              bottom: null,
              width: 268.7183532714844,
              height: 40.0,
              child: GeneratedKisiWidget2(),
            ),
            Positioned(
              left: 46.0,
              top: 446.0,
              right: null,
              bottom: null,
              width: 268.7183532714844,
              height: 40.0,
              child: GeneratedKisiWidget3(),
            ),
            Positioned(
              left: 16.0,
              top: 685.0,
              right: null,
              bottom: null,
              width: 328.0,
              height: 48.0,
              child: GeneratedRectangle193Widget2(),
            ),
            Positioned(
              left: 164.0,
              top: 696.0,
              right: null,
              bottom: null,
              width: 47.0,
              height: 30.0,
              child: GeneratedSKIPWidget(),
            )
          ]),
    ));
  }
}
