import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Ellipse Ellipse 47
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse47Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.20000000298023224,
      child: Container(
        width: 342.0,
        height: 342.0,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M342 171C342 265.441 265.441 342 171 342C76.5593 342 0 265.441 0 171C0 76.5593 76.5593 0 171 0C265.441 0 342 76.5593 342 171Z')
            ..color = Color.fromARGB(255, 255, 198, 0),
        ]),
      ),
    ));
  }
}
