import 'package:flutter/material.dart';

/* UndefinedNode Hover State
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHoverStateWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
