import 'package:flutter/material.dart';
import 'package:flutterapp/eduswappapp/generatedgroup73widget1/generated/GeneratedRectangle1Widget20.dart';
import 'package:flutterapp/eduswappapp/generatedgroup73widget1/generated/GeneratedGroup12Widget7.dart';
import 'package:flutterapp/eduswappapp/generatedgroup73widget1/generated/GeneratedIcbaselinearrowbackWidget17.dart';

/* Group Group 73
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup73Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 352.00543212890625,
      height: 51.5,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: -4.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 65.0,
              child: GeneratedRectangle1Widget20(),
            ),
            Positioned(
              left: 305.99456787109375,
              top: 9.5,
              right: null,
              bottom: null,
              width: 46.010868072509766,
              height: 42.0,
              child: GeneratedGroup12Widget7(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 50.0,
              child: GeneratedIcbaselinearrowbackWidget17(),
            )
          ]),
    ));
  }
}
