import 'package:flutter/material.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget/generated/GeneratedEllipse48Widget1.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget/generated/GeneratedEllipse47Widget1.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget/generated/GeneratedStatusBarWidget1.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget/generated/GeneratedExploretheappWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget/generated/GeneratedRectangle193Widget1.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget/generated/GeneratedLetsStartWidget.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitMorbimae.dart';
import 'package:flutterapp/eduswappapp/generatedexplorewidget/generated/GeneratedOnlineshoppingWidget.dart';

/* Frame Explore
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExploreWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 795.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 15.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 48.0,
                child: GeneratedRectangle193Widget1(),
              ),
              Positioned(
                left: -37.0,
                top: -210.0,
                right: null,
                bottom: null,
                width: 445.0,
                height: 406.0,
                child: GeneratedEllipse48Widget1(),
              ),
              Positioned(
                left: 207.0,
                top: -175.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 342.0,
                child: GeneratedEllipse47Widget1(),
              ),
              Positioned(
                left: -11.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget1(),
              ),
              Positioned(
                left: 137.0,
                top: 707.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 27.0,
                child: GeneratedLetsStartWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 27.0,
                child: GeneratedExploretheappWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 86.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitMorbimae(),
              ),
              Positioned(
                left: 20.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 365.0,
                child: GeneratedOnlineshoppingWidget(),
              )
            ]),
      ),
    ));
  }
}
