import 'package:flutter/material.dart';
import 'package:flutterapp/eduswappapp/generatedstatusbarwidget7/generated/GeneratedStatusIconsWidget7.dart';
import 'package:flutterapp/eduswappapp/generatedstatusbarwidget7/generated/GeneratedTimeLightWidget7.dart';
import 'package:flutterapp/eduswappapp/generatedstatusbarwidget7/generated/GeneratedIndicatorWidget14.dart';
import 'package:flutterapp/eduswappapp/generatedstatusbarwidget7/generated/GeneratedNotchWidget7.dart';

/* Instance Status Bar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStatusBarWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 371.0,
        height: 44.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 30.0,
                child: GeneratedNotchWidget7(),
              ),
              Positioned(
                left: null,
                top: 16.0,
                right: 14.0,
                bottom: null,
                width: 69.0,
                height: 14.0,
                child: GeneratedStatusIconsWidget7(),
              ),
              Positioned(
                left: null,
                top: 8.0,
                right: 71.0,
                bottom: null,
                width: 6.0,
                height: 6.0,
                child: GeneratedIndicatorWidget14(),
              ),
              Positioned(
                left: 21.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 21.0,
                child: GeneratedTimeLightWidget7(),
              )
            ]),
      ),
    ));
  }
}
